### ISSUE TITLE
Why is image file not saving in Firebase Storage ?

### ISSUE THREAD

**Issue by kaka21garuda** [1amageek/Salada#34]
So basically, I try to save a picture into my storage, then save the picture name/url into database.
``` swift      
        let postObject = PostModel()
        postObject.title = title
        postObject.imageTitle = returningImageData(image: imageTitle)
        postObject.content = content
        postObject.save { (ref, error) in
            if error != nil {
                print(error?.localizedDescription)
            }
        }
```
and I got the name and save into the database working successfully. But when I try to download the file, it won't recognize the file name.

```swift
let imageURL = storageRef.child("1489699076238")
        imageURL.downloadURL { (url, error) in
            if error != nil {
                print(error?.localizedDescription)
            } else {
                print("\n\n\nURL: \(url!)")
            }
        }
```

**Comment by 1amageek** [comment]
Thank you for your question.😃
I recommend using FirebaseUI.

Your problem is to miss the reference.
Salada saves the file with the same structure as the structure of Model.

`root/v1/postmodel/$postmodel_id/$postmodel_image_name`

----

In your case you can get like this.
```
postObject.imageTitle?.dataWithMaxSize(1 * 2000 * 2000, completion: { (data, error) in
    if let error: NSError = error {
        print(error)
        return
    }
    let image: UIImage = UIImage(data: data!)
})
```

**Comment by kaka21garuda** [comment]
I tried like what you did in the example of firebaseUI. but how did you do the `sd_setImage` method? what is the type of imageView ?
```swift
User.observeSingle(friend, eventType: .value, block: { (user) in
    if let user: User = user as? User {
        if let ref: FIRStorageReference = user.thumbnail?.ref {
            cell.imageView.sd_setImage(with: ref, placeholderImage: #imageLiteral(resourceName: "account_placeholder"))
        }
    }
 })
```

**Comment by 1amageek** [comment]
Please refer to here for how to use FirebaseUI.

https://github.com/firebase/FirebaseUI-iOS/tree/master/FirebaseStorageUI
