### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by mtfum** [1amageek/Salada#63]
Hi! Nice OSS!

I want to install by Carthage, do you have any plan to support?

Thanks.

**Comment by 1amageek** [comment]
I have no plans to support Carthage. Because Firebase uses cocoapods' Static Frameworks.

**Comment by mtfum** [comment]
Thanks for your reply.
I don't know much about firebase. so  I was satisfied. thanks

**Comment by 1amageek** [comment]
Thank you.
I am looking forward to your contribution.
